apiVersion: apps/v1
kind: Deployment
metadata:
  name: joplin-server
  labels:
    app: joplin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joplin-server
  template:
    metadata:
      labels:
        app: joplin-server
    spec:
      containers:
      - name: joplin-server
        image: florider89/joplin-server:latest
        ports:
        - containerPort: 22300
        env:
        - name: APP_PORT
          value: "22300"
        - name: APP_BASE_URL
          value: "http://localhost:22300"
        - name: DB_CLIENT
          value: "pg"
        - name: POSTGRES_PASSWORD
          value: "joplinpassword"
        - name: POSTGRES_DATABASE
          value: "joplin"
        - name: POSTGRES_USER
          value: "joplin"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_HOST
          value: "joplin-postgres"
        volumeMounts:
        - name: joplin-data
          mountPath: /home/joplin/.joplin-server
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: joplin-data
        persistentVolumeClaim:
          claimName: joplin-data-pvc
