apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: n8n
  labels:
    app: postgres
    component: database
  annotations:
    description: "PostgreSQL database for n8n workflows"
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
