apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    name: blinko
  labels:
    io.kompose.service: blinko
  name: blinko
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: blinko
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: blinko
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: postgresql://postgres:mysecretpassword@postgres:5440/postgres
          image: blinkospace/blinko:latest
          name: blinko
          resources:
            limits:
              cpu: "1"
              memory: "1024Mi"
            requests:
              cpu: "1"
              memory: "1024Mi"
          ports:
            - containerPort: 1111
      restartPolicy: Always
