apiVersion: apps/v1
kind: Deployment
metadata:
  name: blinko
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blinko
  template:
    metadata:
      labels:
        app: blinko
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
        - env:
            - name: DATABASE_URL
              value: postgresql://postgres:mysecretpassword@postgres:5440/postgres
          image: blinkospace/blinko:latest
          name: blinko
          resources:
            limits:
              cpu: "1"
              memory: "1024Mi"
            requests:
              cpu: "1"
              memory: "1024Mi"
          ports:
            - containerPort: 1111
      restartPolicy: Always
