apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    name: blinko
  labels:
    io.kompose.service: blinko
  name: blinko
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: blinko
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: blinko
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: postgresql://postgres:mysecretpassword@postgres:5432/postgres
            - name: NEXTAUTH_SECRET
              value: my_ultra_secure_nextauth_secret
            - name: NODE_ENV
              value: production
          image: blinkospace/blinko:latest
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://blinko:1111/
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
          name: blinko
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          ports:
            - containerPort: 1111
              protocol: TCP
      restartPolicy: Always
