apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: ollama-service
  namespace: ollama
spec:
  ports:
  - port: 11434
    protocol: TCP
    targetPort: 11434
  selector:
    app: ollama
  type: ClusterIP
