apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations: {}
  name: ollama
  namespace: ollama
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-raid
