apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  name: ollama
  namespace: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ollama
    spec:
      nodeSelector:
        accelerator: nvidia-gpu
      runtimeClassName: nvidia
      containers:
      - name: ollama
        image: ollama/ollama
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
            nvidia.com/gpu: "1"
          requests:
            cpu: "1"
            memory: "2Gi"
            nvidia.com/gpu: "1"
        env:
        - name: OLLAMA_CONTEXT_LENGTH
          value: "8192"
        - name: OLLAMA_KEEP_ALIVE
          value: "6h"
        - name: OLLAMA_GPU_COUNT
          value: "1"
        # - name: OLLAMA_SCHED_SPREAD
          # value: "1"
        ports:
        - name: http
          containerPort: 11434
          protocol: TCP
        - name: grpc
          containerPort: 11434
          protocol: TCP
        volumeMounts:
        - name: ollama
          mountPath: /root/.ollama/models
      volumes:
      - name: ollama
        persistentVolumeClaim:
          claimName: ollama
