apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres

resources:
  - postgres-deployment.yaml
  - postgres-init-script.yaml
  - postgres-pvc.yaml
  - postgres-service.yaml

secretGenerator:
  - name: postgres-secrets
    namespace: kube-system
    envs:
      - ../.env