apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      nodeSelector:
        accelerator: nvidia-gpu
      runtimeClassName: nvidia
      initContainers:
      - name: init-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /root/.ollama/models && chmod -R 755 /root/.ollama/models"]
        volumeMounts:
        - name: ollama-storage
          mountPath: /root/.ollama/models
      containers:
      - name: ollama
        image: ollama/ollama
        resources:
          limits:
            nvidia.com/gpu: "1"
            cpu: "1"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "4Gi"
            nvidia.com/gpu: "1"
        env:
        - name: OLLAMA_CONTEXT_LENGTH
          value: "8192"
        - name: OLLAMA_KEEP_ALIVE
          value: "6h"
        ports:
        - containerPort: 11434
        volumeMounts:
        - name: ollama-storage
          mountPath: /root/.ollama/models
      volumes:
      - name: ollama-storage
        persistentVolumeClaim:
          claimName: ollama-storage
